### ISSUE TITLE
Behavior of Transcript

### ISSUE THREAD

**Issue by marceltaeumel** [fniephaus/filetreeCI#1]
Is `Transcript`actually a `TranscriptStream`? I doubt that because of this:

https://travis-ci.org/hpi-swa/signals/jobs/72099074

https://github.com/hpi-swa/signals/blob/master/repository/Signals.package/SignalTest.class/instance/test35SignalSpyVerboseMode.st

Line 16 in the test fails on TravisCI.

**Comment by fniephaus** [comment]
`Transcript` is the standard `TranscriptStream`, but `Transcript>>show:` is overridden by this extension method:
https://github.com/fniephaus/filetreeCI/blob/build/scripts/MetacelloBuilderTravisCI.st#L116-L117

And that's the problem :smile:
